name: Zapier Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.9.0'
      - run: npm install -g zapier-platform-cli
      - run: npm install
      - run: npm run build --if-present
      - run: zapier test
        env:
          CI: true